<?php
// Full curriculum definition for the Data Analysis track.
// Each entry carries `stage` (grouping/ordering on the dashboard) and `skill`
// (one of: python, pandas, cleaning, statistics, sql, visualization, eda,
// projects — used by the dashboard's skills-breakdown panel).
return [
    'intro' => [
        'title_ar' => 'مقدمة في تحليل البيانات',
        'title_en' => 'Intro to Data Analysis',
        'desc_ar'  => 'إيه هو تحليل البيانات، ومراحل عملية التحليل من السؤال للقرار.',
        'desc_en'  => 'What data analysis is, and the process stages from question to decision.',
        'stage' => 1, 'stage_title_ar' => 'أساسيات تحليل البيانات', 'stage_title_en' => 'Data Analysis Foundations', 'skill' => 'python',
    ],
    'python-for-data' => [
        'title_ar' => 'Python لتحليل البيانات: أساسيات Pandas',
        'title_en' => 'Python for Data: Pandas Basics',
        'desc_ar'  => 'DataFrame، قراءة البيانات، واختيار الأعمدة والصفوف — بالتنفيذ الفعلي.',
        'desc_en'  => 'DataFrames, reading data, and selecting rows/columns — with real execution.',
        'stage' => 4, 'stage_title_ar' => 'أساسيات Pandas', 'stage_title_en' => 'Pandas Fundamentals', 'skill' => 'pandas',
    ],
    'numpy-essentials' => [
        'title_ar' => 'أساسيات NumPy',
        'title_en' => 'NumPy Essentials',
        'desc_ar'  => 'Arrays، الأبعاد، والعمليات المتجهة (Vectorized) — الأساس اللي Pandas مبني عليه.',
        'desc_en'  => 'Arrays, dimensions, and vectorized operations — the foundation Pandas is built on.',
        'stage' => 3, 'stage_title_ar' => 'أساسيات NumPy', 'stage_title_en' => 'NumPy Essentials', 'skill' => 'python',
    ],
    'data-transformation-deep-dive' => [
        'title_ar' => 'تحويل البيانات بعمق: Merge, Join, Pivot',
        'title_en' => 'Data Transformation Deep Dive: Merge, Join, Pivot',
        'desc_ar'  => 'دمج جداول، Pivot Tables، وConcatenate — لما بياناتك موزعة على أكتر من مصدر.',
        'desc_en'  => 'Merging tables, Pivot Tables, and Concatenate — when your data lives across multiple sources.',
        'stage' => 6, 'stage_title_ar' => 'تحويل واستكشاف البيانات', 'stage_title_en' => 'Data Transformation & Exploration', 'skill' => 'pandas',
    ],
    'data-cleaning' => [
        'title_ar' => 'تنظيف البيانات',
        'title_en' => 'Data Cleaning',
        'desc_ar'  => 'التعامل مع القيم الناقصة والمكررة والبيانات غير المتسقة.',
        'desc_en'  => 'Handling missing values, duplicates, and inconsistent data.',
        'stage' => 5, 'stage_title_ar' => 'تنظيف البيانات', 'stage_title_en' => 'Data Cleaning', 'skill' => 'cleaning',
    ],
    'messy-real-world-data' => [
        'title_ar' => 'التعامل مع بيانات فوضوية حقيقية',
        'title_en' => 'Working with Real-World Messy Data',
        'desc_ar'  => 'قيم ناقصة، تكرار، وأعمدة مختلطة الأنواع — تحدي أصعب وأقرب لواقع الشغل.',
        'desc_en'  => 'Missing values, duplicates, and mixed-type columns — a harder challenge closer to real work.',
        'stage' => 5, 'stage_title_ar' => 'تنظيف البيانات', 'stage_title_en' => 'Data Cleaning', 'skill' => 'cleaning',
    ],
    'data-exploration' => [
        'title_ar' => 'الاستكشاف والتحليل الوصفي',
        'title_en' => 'Exploratory Data Analysis',
        'desc_ar'  => 'groupby، التجميعات، والإحصاءات الوصفية لفهم البيانات بسرعة.',
        'desc_en'  => 'groupby, aggregations, and descriptive statistics to understand data fast.',
        'stage' => 10, 'stage_title_ar' => 'التحليل الاستكشافي (EDA)', 'stage_title_en' => 'Exploratory Data Analysis', 'skill' => 'eda',
    ],
    'statistics-basics' => [
        'title_ar' => 'أساسيات الإحصاء',
        'title_en' => 'Statistics Basics',
        'desc_ar'  => 'المتوسط والوسيط والانحراف المعياري — وليه بيفرقوا في تفسير البيانات.',
        'desc_en'  => 'Mean, median, and standard deviation — and why they matter for interpreting data.',
        'stage' => 7, 'stage_title_ar' => 'الإحصاء لتحليل البيانات', 'stage_title_en' => 'Statistics for Data Analysis', 'skill' => 'statistics',
    ],
    'outliers-and-correlation' => [
        'title_ar' => 'القيم الشاذة والارتباط',
        'title_en' => 'Outliers & Correlation',
        'desc_ar'  => 'طريقة IQR لاكتشاف القيم الشاذة، وحساب الارتباط بين متغيرين — مع تحذير Correlation ≠ Causation.',
        'desc_en'  => 'The IQR method for detecting outliers, and computing correlation between variables — with the Correlation ≠ Causation warning.',
        'stage' => 7, 'stage_title_ar' => 'الإحصاء لتحليل البيانات', 'stage_title_en' => 'Statistics for Data Analysis', 'skill' => 'statistics',
    ],
    'sql-for-analysis' => [
        'title_ar' => 'SQL لتحليل البيانات',
        'title_en' => 'SQL for Analysis',
        'desc_ar'  => 'استعلامات SELECT وGROUP BY وJOIN لسحب البيانات من قاعدة بيانات.',
        'desc_en'  => 'SELECT, GROUP BY, and JOIN queries to pull data from a database.',
        'stage' => 8, 'stage_title_ar' => 'SQL لتحليل البيانات', 'stage_title_en' => 'SQL for Data Analysis', 'skill' => 'sql',
    ],
    'data-visualization' => [
        'title_ar' => 'تصور البيانات',
        'title_en' => 'Data Visualization',
        'desc_ar'  => 'رسم بياني حقيقي بـ Matplotlib عشان توصّل رسالة البيانات بصريًا.',
        'desc_en'  => 'Real charts with Matplotlib to communicate data visually.',
        'stage' => 9, 'stage_title_ar' => 'تصور البيانات', 'stage_title_en' => 'Data Visualization', 'skill' => 'visualization',
    ],
    'time-series-basics' => [
        'title_ar' => 'أساسيات السلاسل الزمنية',
        'title_en' => 'Time Series Basics',
        'desc_ar'  => 'بيانات مرتبطة بالوقت — اتجاهات، موسمية، ومتوسطات متحركة بـ Pandas.',
        'desc_en'  => 'Time-indexed data — trends, seasonality, and rolling averages with Pandas.',
        'stage' => 6, 'stage_title_ar' => 'تحويل واستكشاف البيانات', 'stage_title_en' => 'Data Transformation & Exploration', 'skill' => 'pandas',
    ],
    'business-analysis-kpis' => [
        'title_ar' => 'التحليل التجاري ومؤشرات الأداء (KPIs)',
        'title_en' => 'Business Analysis & KPIs',
        'desc_ar'  => 'الإيراد، الربح، هامش الربح، ومعدل النمو — تحسب مؤشرات حقيقية من بيانات حقيقية.',
        'desc_en'  => 'Revenue, profit, margin, and growth rate — calculating real KPIs from real data.',
        'stage' => 11, 'stage_title_ar' => 'التحليل التجاري', 'stage_title_en' => 'Business Analysis', 'skill' => 'eda',
    ],
    'project-marketing-analytics' => [
        'title_ar' => '🚀 مشروع: تحليل حملات تسويقية',
        'title_en' => '🚀 Project: Marketing Campaign Analysis',
        'desc_ar'  => 'أنهي حملة أفضل أداء؟ أعلى ROI؟ هل زيادة الإنفاق بتزود الإيراد فعلًا؟',
        'desc_en'  => 'Which campaign performs best? Highest ROI? Does more spend actually mean more revenue?',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'project-customer-analytics' => [
        'title_ar' => '🚀 مشروع: تحليل العملاء',
        'title_en' => '🚀 Project: Customer Analytics',
        'desc_ar'  => 'أعلى العملاء قيمة، شرائح العملاء، ومتوسط قيمة الطلب.',
        'desc_en'  => 'Top customers by value, customer segments, and average order value.',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'project-hr-analytics' => [
        'title_ar' => '🚀 مشروع: تحليلات الموارد البشرية',
        'title_en' => '🚀 Project: HR Analytics',
        'desc_ar'  => 'توزيع الرواتب، مقارنة الأقسام، والعلاقة بين الأداء وترك الخدمة.',
        'desc_en'  => 'Salary distribution, department comparison, and the performance-attrition relationship.',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'project-housing-analysis' => [
        'title_ar' => '🚀 مشروع: تحليل أسعار العقارات',
        'title_en' => '🚀 Project: Housing Price Analysis',
        'desc_ar'  => 'توزيع الأسعار حسب المنطقة، العلاقة بين المساحة والسعر، والقيم الشاذة.',
        'desc_en'  => 'Price distribution by location, the area-price relationship, and outliers.',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'project-ecommerce-eda' => [
        'title_ar' => '🚀 مشروع: تحليل استكشافي كامل لمتجر إلكتروني',
        'title_en' => '🚀 Project: Full E-Commerce EDA',
        'desc_ar'  => 'دورة EDA كاملة على 1500 طلب حقيقي — من الفحص الأول للاستنتاجات النهائية.',
        'desc_en'  => 'A complete EDA cycle on 1,500 real orders — from first inspection to final conclusions.',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'capstone-analysis' => [
        'title_ar' => '🚀 مشروع: تحليل المبيعات الكامل',
        'title_en' => '🚀 Project: Full Sales Analysis',
        'desc_ar'  => 'تحليل بيانات حقيقية من السؤال للرسم البياني للاستنتاج.',
        'desc_en'  => 'Analyzing real data from question to chart to conclusion.',
        'stage' => 13, 'stage_title_ar' => 'مشاريع واقعية', 'stage_title_en' => 'Real-World Projects', 'skill' => 'projects',
    ],
    'final-capstone-project' => [
        'title_ar' => '🏆 مشروع التخرج: بيانات لم تراها من قبل',
        'title_en' => '🏆 Final Capstone: A Dataset You\'ve Never Seen',
        'desc_ar'  => 'دورة تحليل كاملة (13 خطوة) على Dataset جديد كليًا — بدون أي درس يشرحه مسبقًا.',
        'desc_en'  => 'A complete 13-step analysis cycle on a brand-new dataset — with no lesson explaining it beforehand.',
        'stage' => 14, 'stage_title_ar' => 'مشروع التخرج والتقييم النهائي', 'stage_title_en' => 'Final Capstone & Assessment', 'skill' => 'projects',
    ],
    'final-assessment' => [
        'title_ar' => '🏆 التقييم النهائي العملي',
        'title_en' => '🏆 Final Practical Assessment',
        'desc_ar'  => '9 مهام عملية على Dataset جديد — فحص، تنظيف، KPIs، SQL، رسوم بيانية، واستنتاجات.',
        'desc_en'  => '9 hands-on tasks on a new dataset — inspect, clean, KPIs, SQL, charts, and insights.',
        'stage' => 14, 'stage_title_ar' => 'مشروع التخرج والتقييم النهائي', 'stage_title_en' => 'Final Capstone & Assessment', 'skill' => 'projects',
    ],
    'careers' => [
        'title_ar' => 'العمل في تحليل البيانات',
        'title_en' => 'Data Analysis Careers',
        'desc_ar'  => 'Data Analyst مقابل Data Scientist، والمهارات المطلوبة لكل مسار.',
        'desc_en'  => 'Data Analyst vs Data Scientist, and the skills each path requires.',
        'stage' => 1, 'stage_title_ar' => 'أساسيات تحليل البيانات', 'stage_title_en' => 'Data Analysis Foundations', 'skill' => 'python',
    ],
];
