<?php
// Full curriculum definition for the Full Stack Developer track.
// Some stages have an 'external' key pointing directly at the matching lesson
// in the Front-End or PHP Back-End tracks instead of duplicating content —
// paths are relative to this file's location (fullstack/lessons/... equivalent).
return [
    'intro' => [
        'title_ar' => 'معنى Full Stack Developer',
        'title_en' => 'What is a Full Stack Developer?',
        'desc_ar'  => 'مقال مهم لبدأ التعرف على الوظيفة قبل ما تدخل فيها.',
        'desc_en'  => 'An important read to understand the role before diving in.',
    ],
    'setup' => [
        'title_ar' => 'الأدوات والإعدادات',
        'title_en' => 'Tools & Setup',
        'desc_ar'  => 'برنامج الكتابة، المتصفح، والإعدادات اللازمة قبل ما تبدأ.',
        'desc_en'  => 'Your code editor, browser, and the setup you need before starting.',
    ],
    'faq' => [
        'title_ar' => 'أهم الأسئلة التي يسألها من يبدأ التعلم',
        'title_en' => 'Common Questions Before You Start',
        'desc_ar'  => 'إجابات على أكتر الأسئلة اللي بتدور في بالك قبل البدء.',
        'desc_en'  => 'Answers to the most common questions before you begin.',
    ],
    'html' => [
        'title_ar' => 'تعلم لغة HTML',
        'title_en' => 'Learn HTML',
        'desc_ar'  => 'لغة بنية الصفحات — أساس أي حاجة هتشوفها على الويب.',
        'desc_en'  => 'The page-structure language — the foundation of everything on the web.',
        'external' => '../frontend/lessons/html.php',
    ],
    'css' => [
        'title_ar' => 'تعلم لغة CSS',
        'title_en' => 'Learn CSS',
        'desc_ar'  => 'اللغة المسؤولة عن الشكل: ألوان، خطوط، أبعاد، Flexbox وGrid.',
        'desc_en'  => 'The language responsible for appearance: colors, fonts, sizing, Flexbox and Grid.',
        'external' => '../frontend/lessons/css.php',
    ],
    'html-css-projects' => [
        'title_ar' => '4 تصاميم وتطبيقات على HTML + CSS',
        'title_en' => 'HTML + CSS Practice Projects',
        'desc_ar'  => 'توظيف HTML وCSS في تصاميم وتطبيقات عملية متنوعة.',
        'desc_en'  => 'Applying HTML and CSS in varied hands-on design projects.',
        'external' => '../frontend/lessons/html-css-projects.php',
    ],
    'javascript' => [
        'title_ar' => 'تعلم لغة JavaScript',
        'title_en' => 'Learn JavaScript',
        'desc_ar'  => 'اللغة المسؤولة عن السلوك والتفاعل — أساسيات اللغة ومعايير ECMAScript.',
        'desc_en'  => 'The language responsible for behavior and interactivity.',
        'external' => '../frontend/lessons/javascript.php',
    ],
    'javascript-practice' => [
        'title_ar' => 'التطبيق على JavaScript',
        'title_en' => 'JavaScript Practice',
        'desc_ar'  => 'تحديات ومسائل مستمرة معك طول المسار لتثبيت أساسيات اللغة.',
        'desc_en'  => 'Ongoing challenges throughout the track to solidify the fundamentals.',
        'external' => '../frontend/lessons/javascript-practice.php',
    ],
    'js-project' => [
        'title_ar' => 'مشروع كامل بـ JavaScript فقط',
        'title_en' => 'A Full Vanilla JavaScript Project',
        'desc_ar'  => 'تصميم موقع وعمل مميزاته بـ JavaScript فقط من غير أي إطار عمل.',
        'desc_en'  => 'Designing a site and building its features with plain JavaScript.',
        'external' => '../frontend/lessons/js-project.php',
    ],
    'responsive' => [
        'title_ar' => 'تصميم متجاوب بدون إطار عمل',
        'title_en' => 'Responsive Design from Scratch',
        'desc_ar'  => 'مفهوم الـ Responsive Design الأساسي قبل ما تستخدم أي framework.',
        'desc_en'  => 'The core concept of Responsive Design before relying on a framework.',
        'external' => '../frontend/lessons/responsive.php',
    ],
    'frameworks' => [
        'title_ar' => 'أطر العمل: Bootstrap وTailwind',
        'title_en' => 'Frameworks: Bootstrap & Tailwind',
        'desc_ar'  => 'تصاميم عملية بأشهر أطر العمل والمكتبات في التنسيق.',
        'desc_en'  => 'Practical designs using the most popular CSS frameworks.',
        'external' => '../frontend/lessons/frameworks.php',
    ],
    'sass' => [
        'title_ar' => 'تعلم SASS',
        'title_en' => 'Learn SASS',
        'desc_ar'  => 'مزايا لغات البرمجة جوه CSS: متغيرات، Nesting، وMixins.',
        'desc_en'  => 'Programming-language features inside CSS: variables, nesting, mixins.',
        'external' => '../frontend/lessons/sass.php',
    ],
    'pug' => [
        'title_ar' => 'تعلم Pug.js',
        'title_en' => 'Learn Pug.js',
        'desc_ar'  => 'Template Engine بيديك مزايا لغات البرمجة أثناء كتابة HTML.',
        'desc_en'  => 'A template engine bringing programming-language features to HTML.',
        'external' => '../frontend/lessons/pug.php',
    ],
    'gulp' => [
        'title_ar' => 'تعلم Gulp.js',
        'title_en' => 'Learn Gulp.js',
        'desc_ar'  => 'أتمتة المهام المتكررة بدل ما تعملها يدويًا.',
        'desc_en'  => 'Automating repetitive tasks instead of doing them manually.',
        'external' => '../frontend/lessons/gulp.php',
    ],
    'testing' => [
        'title_ar' => 'اختبار JavaScript بـ Jest',
        'title_en' => 'JavaScript Unit Testing with Jest',
        'desc_ar'  => 'اختبار برمجياتك تلقائيًا — مهارة أساسية في أي بيئة عمل حقيقية.',
        'desc_en'  => 'Automatically testing your code — essential in any real workplace.',
        'external' => '../frontend/lessons/testing.php',
    ],
    'vue' => [
        'title_ar' => 'إطار العمل Vue.js',
        'title_en' => 'The Vue.js Framework',
        'desc_ar'  => 'واحد من أسهل وأقوى أطر عمل JavaScript لبناء تطبيقات ويب تفاعلية.',
        'desc_en'  => 'One of the easiest, most powerful JavaScript frameworks.',
        'external' => '../frontend/lessons/vue.php',
    ],
    'php' => [
        'title_ar' => 'تعلم لغة PHP لبناء تطبيقات ومواقع الويب',
        'title_en' => 'Learn PHP for Web Applications',
        'desc_ar'  => 'من أشهر لغات الـ Backend، مجانية وسهلة التعلم وليها دعم كبير.',
        'desc_en'  => 'One of the most popular Backend languages — free, easy, widely supported.',
        'external' => '../php-backend/lessons/stage1.php',
    ],
    'mysql' => [
        'title_ar' => 'تعلم MySQL للتعامل مع قواعد البيانات',
        'title_en' => 'Learn MySQL for Databases',
        'desc_ar'  => 'قاعدة البيانات المسؤولة عن تخزين واسترجاع بيانات تطبيقك.',
        'desc_en'  => 'The database responsible for storing and retrieving your app\'s data.',
        'external' => '../php-backend/lessons/stage4.php',
    ],
    'contact-form-project' => [
        'title_ar' => 'تطبيق عملي: نموذج تواصل (Contact Form)',
        'title_en' => 'Practical Project: Contact Form',
        'desc_ar'  => 'تصميم وبرمجة نموذج تواصل كامل يوظّف HTML/CSS وPHP مع بعض.',
        'desc_en'  => 'Designing and coding a full Contact Form combining HTML/CSS and PHP.',
    ],
    'online-store-project' => [
        'title_ar' => 'تطبيق عملي: متجر إلكتروني (Online Store)',
        'title_en' => 'Practical Project: Online Store',
        'desc_ar'  => 'برمجة متجر إلكتروني كامل يوظّف كل حاجة اتعلمتها في المسار.',
        'desc_en'  => 'Building a complete online store putting the whole track together.',
    ],
    'cli-git' => [
        'title_ar' => 'Command Line و Git/GitHub',
        'title_en' => 'Command Line & Git/GitHub',
        'desc_ar'  => 'أوامر التيرمينال الأساسية، Git للتحكم بالإصدارات، ورفع مشروعك على GitHub.',
        'desc_en'  => 'Essential terminal commands, Git for version control, and GitHub.',
        'external' => '../php-backend/lessons/tools.php',
    ],
];
